DROP TABLE IF EXISTS Kayttaja CASCADE; 
DROP TABLE IF EXISTS Omistaja CASCADE;
DROP TABLE IF EXISTS Omistaja_Astiat CASCADE;
DROP TABLE IF EXISTS Astiat CASCADE;
DROP TABLE IF EXISTS Brandi CASCADE;
DROP TABLE IF EXISTS Brandi_Astiat CASCADE;

